# Site settings
title:          theora's blog
description:    ""
baseurl:        ""
url:            ""

# Google Analytics
google_analytics: UA—124330215-1

# Author
author:
  name:
  url:
  email:        summerinloving@gmail.com

# Build settings
markdown:       kramdown
include:
  - _posts

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
